// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmEkOGgZIKE3FSjZP8KRnh1CAUTkjU1v0',
    appId: '1:624574025589:web:12390ad96c642591de0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    authDomain: 'pondstat-7c430.firebaseapp.com',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
    measurementId: 'G-VSEL8H3T0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRvFOI1Jhg63IjZ1cw4QUkD-GyfdDJ84Y',
    appId: '1:624574025589:android:0be1efe3c4bfc7c8de0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDACjaDIAe_ceOZrjxeQuV5xN5bfGClX0',
    appId: '1:624574025589:ios:82c3a68720140533de0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
    androidClientId:
        '624574025589-5gjmf663uvnd81kiu5bilojmahe1pnot.apps.googleusercontent.com',
    iosClientId:
        '624574025589-hpa5lda8qq5maa8pk4g6gcp8bhrbkhj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pondstat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDACjaDIAe_ceOZrjxeQuV5xN5bfGClX0',
    appId: '1:624574025589:ios:82c3a68720140533de0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
    androidClientId:
        '624574025589-5gjmf663uvnd81kiu5bilojmahe1pnot.apps.googleusercontent.com',
    iosClientId:
        '624574025589-hpa5lda8qq5maa8pk4g6gcp8bhrbkhj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pondstat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmEkOGgZIKE3FSjZP8KRnh1CAUTkjU1v0',
    appId: '1:624574025589:web:12390ad96c642591de0d3c',
    messagingSenderId: '624574025589',
    projectId: 'pondstat-7c430',
    authDomain: 'pondstat-7c430.firebaseapp.com',
    storageBucket: 'pondstat-7c430.firebasestorage.app',
    measurementId: 'G-VSEL8H3T0V',
  );
}
